CHANNEL_ACCESS_TOKEN = ""
CHANNEL_SECRET = ""
LINE_USER_ID = ''
OPENAI_API_KEY = ''
IMGUR_CLIENT_ID = ''
HACKMD_USER_NAME = ''
HACKMD_API_TOKEN = ''
TODO_NOTE_ID = '' #  paste your fixed TODO note id
TEMP_NOTE_ID = '' # paste your fixed TEMP note id
AI_NOTE_ID = '' # paste your fixed OpenAI note id