# Modify this Procfile to fit your needs
# web: gunicornapp-hellofly:app
# web: gunicorn app_for_tools:app
# web: gunicorn app_for_openaibot:app 
# web: gunicorn app_for_hackmdbot:app
web: gunicorn app:app